# Generated by Django 3.1.7 on 2021-03-24 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=128, unique=True, verbose_name='Empresa, S.A')),
                ('telefono', models.CharField(max_length=50, verbose_name='111111111')),
                ('horarioAtencion', models.CharField(max_length=256, verbose_name='Lunes-Viernes: 9:00 am a 18:00 pm')),
                ('quienesSomos', models.CharField(max_length=1024, verbose_name='XXXXXXXXXXXXXXXXXXXXXXXXXXX')),
                ('latitud', models.DecimalField(decimal_places=20, max_digits=20, verbose_name='-32.89035681895765')),
                ('longitud', models.DecimalField(decimal_places=20, max_digits=20, verbose_name=' -68.847745651633')),
                ('domicilio', models.CharField(max_length=256, verbose_name='San Martin 1580, Godoy Cruz, Mendoza')),
                ('email', models.EmailField(max_length=254, verbose_name='empresa@empresa.com')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128, verbose_name='Título Noticia')),
                ('resumen', models.CharField(max_length=1024, verbose_name='Resumen Noticia')),
                ('imagen', models.ImageField(upload_to='imagenes/imagenesNoticias/%Y/%m/%d/')),
                ('contenidoHTML', models.CharField(max_length=20480, verbose_name='Contenido HTML')),
                ('publicada', models.CharField(choices=[('Y', 'Y'), ('N', 'N')], help_text='Selecione Y si fue publicada, contrario seleccione N', max_length=1)),
                ('fechaPublicacion', models.DateField(auto_now=True, verbose_name='5/05/2021')),
                ('fechaModificacion', models.DateField(auto_now_add=True, verbose_name='5/5/2021')),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VisualizadorEmpresas.empresa')),
            ],
            options={
                'ordering': ['-fechaPublicacion'],
            },
        ),
    ]
